# This config file will disable most of the metadata consistency checks.
# It is mainly intended to demonstrate how to disable default settings, 
# But it may also be useful for testing purposes.

output:
    name: "{dune_mc.gen_fcl_filename}_{dune.campaign}_{dune.config_file}_{core.application.name}_{core.application.version}_hists"
    namespace: "usertests"

metadata:
    # ~consistent:  # Reduced set of consistency checks ('~' indicates override)
    #   - "core.run_type"
    #   - "core.file_format"
    #   - "core.data_tier"
    #   - "core.application.name"
    required:
      - "~core.runs" # Don't require core.runs ('~' indicates negation)
merging:
    method:
        name: "lar"
        cfg: "triggerana_dune10kt_1x2x2.fcl"
        metadata: {"core.data_tier":"root-tuple"}
  
